export const actionList ={
    CREATE_CHAT: 'CREATE_CHAT',
    CREATE_CHAT_ERROR: 'CREATE_CHAT_ERROR',
    SEND_MESSAGE: 'SEND_MESSAGE',
    SEND_MESSAGE_ERROR: 'SEND_MESSAGE_ERROR',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',
    INPUT_MESSAGE: 'INPUT_MESSAGE',
    SEARCH: 'SEARCH',
    STAR: 'STAR',
    STAR_ERROR: 'STAR_ERROR'
}