export const actionList ={
    CREATE_CHAT: 'CREATE_CHAT',
    SEND_MESSAGE: 'SEND_MESSAGE',
    SEND_MESSAGE_ERROR: 'SEND_MESSAGE_ERROR',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT'
}